# Generated by Django 4.1.3 on 2022-11-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familiar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nac',
        ),
    ]
