# Generated by Django 4.1.3 on 2022-11-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiar', '0002_remove_familiar_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='parentezco',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
